### ISSUE TITLE
Doesn't work with propboe

### ISSUE THREAD

**Issue by jjinkou2** [konimaru/waitvid.2048#12]
I don't know why but i can't make any of them work on my propboe. VGA is connected from  8-15. i know it works since i could compile a previous version: for instance your driver here works correctly https://forums.parallax.com/discussion/146678/vga-launcher-vga-demos-for-propboe-users

**Comment by konimaru** [comment]
It's not just a question of wiring your stuff up. There is also a software part to it (i.e. **vcfg** needs to be setup with the **pin group**).

If you can tell me which driver you want to use I'll have a look and let you know what needs changing.

**Comment by jjinkou2** [comment]
i would like to use the 50HxRAM. 
I changed : 
```
  vpin    = $0FC                                ' pin group mask
  vgrp    = 2                                   ' pin group
sgrp = 2 ' pin group sync
```
to 
```
  vpin    = $0FF                                ' pin group mask
  vgrp    = 1                                   ' pin group
sgrp = 1                                     ' pin group sync
```
without result. 

mind if  i ask for a suggestion ?  why not integrate a pingroup inside the init . So when you call it inside the demo it could be: 
`vga.init(pingroup). `

So that the user of the driver never mess inside the driver. 

But i know that would break every demo.  and may be that is intentional from your part.

**Comment by konimaru** [comment]
**[valid for version 0.8]**
If you just want to move **pin group** then you should only touch **vgrp** and **sgrp**, leave **vpin** alone ($FC). In your case that would be $FC/1/1. The $FF setting demands different **pin groups** for sync and video which I believe is not the case for your setup.

re: parameters, at the time there were basically two ways of doing things, parameters or constants. I opted for the latter. That being said, there is at least one driver which does take the group as a parameter but that's simply because the user needed 4 instances of said driver for his multi-display console (and would otherwise have needed 4 drivers instead of one). Depending on how strong you feel about it, just file a enhancement request and I can have a look.

**Comment by jjinkou2** [comment]
i'll test tonight your modifications when i'm at home .
no need to change anything , i was just curious about the rational behind. 

thank you.

**Comment by jjinkou2** [comment]
Still have a problem with $FC/1/1. I have only these led on (which shows that VGA is receiving signal on ): 
- pin 9
 - pin 10 & 11 corresponding B0B1(blue OK)
- only pin 13 (G1)
I have no signal on 8, 12,14,15

**Comment by konimaru** [comment]
Ah, would have been good to know. **bst** has a problem with PASM like `long +4` which is downgraded to `long 0`. Good to know you got it working. Have fun!
